### ISSUE TITLE
How to retry job that are not acknowledged ? 

### ISSUE THREAD

**Issue by s8sg** [adjust/rmq#101]
I'm trying to handle a requirement where a consumer can get killed. And when it comes back it should retry to task it was performing.

I have 2 push queue configured and when a task fails, the delivery gets `Push`ed to the next queue. If successful it is `Ack`ed. 

If a consumer gets killed neither the `delivery.Ack()` or `delivery.Push()` will be called. What is the way to retry the delivery that was not `acknowledged` ?

**Comment by wellle** [comment]
See https://github.com/adjust/rmq#cleaner :v:
