### ISSUE TITLE
Can two consumer consume same queue?

### ISSUE THREAD

**Issue by gearintellix** [adjust/rmq#107]
I just want clarification regarding consumer behavior, because every consumer need a name

```go
taskConsumer := &TaskConsumer{}
name, err := taskQueue.AddConsumer("task-consumer", taskConsumer)
```
So i think the purpose is to be designed as consumer group (in Kafka), which is if there's two consumer with different name will be receive same messages, or it's only for consumer identity only?

thank you

**Comment by wellle** [comment]
Hey! The tag you pass to `AddConsumer` does NOT work like a Kafka consumer group. You can use different tags for your consumers or even the same one, as internally a random suffix it attached to make the interval consumer names unique. These names are used for internal book keeping. Regardless of what tag you use there, all consumers will work in a single group. Each messages gets consumed by exactly one consumer. There's no way to have multiple consumers to consume the same delivery.

**Comment by gearintellix** [comment]
got it, thank for your response
