### ISSUE TITLE
Trying to use rmq against a clustered Redis/Elasticcache Db. keep getting the "MOVED" error.

### ISSUE THREAD

**Issue by afernandezod** [adjust/rmq#110]
After reading the "MOVED" error is due to instantiate a client to a clustered redis Db, I tried several options using redis.NewClusterCLienat, redis.NewClient and when ready to establish the connection I tried rmq.OpenConnectionWithRedisClient in order to once having the connection active be able to open the queue (rmq-connection.OpenQueue().

Not sure if I am missing something or clustered redis Db are not in the scope for rmq.

Any help is greatly appreciated. 

Here part of the code:

```go
func redisConnect(quename string) rmq.Queue {
	redisClient := redis.NewClient(&redis.Options{
		Addr: Host,
		DB:   0,
	})

	nodes := strings.Split(Hosts, ",")
	c := redis.NewClusterClient(&redis.ClusterOptions{
		Addrs: nodes,
		NewClient: func(opt *redis.Options) *redis.Client {
			opt.Addr = Host
			opt.DB = 0
			return redis.NewClient(opt)
		},
	})

	ctx := context.Background()
	pingError := c.Ping(ctx).Err()

	if c.Ping(ctx).Err() != nil {
		panic("Unable to connect to redis ")
	}

	connection, err := rmq.OpenConnectionWithRedisClient("TCP", redisClient, nil)
	if err != nil {
		panic(err)
	}

	coolqueue, err := connection.OpenQueue(quename)
	if err != nil {
		panic(err)
	}

	return coolqueue
}
```

Thanks.

**Comment by si3nloong** [comment]
I think it was your setup issue, try to amend your config as below

`redis.NewClusterClient(&redis.ClusterOptions{
		Addrs: nodes,
	})```

**Comment by afernandezod** [comment]
@si3nloong Thanks. I tried that also and same results. I think as @wellle mentioned rmq hasn't been exposed to this flavor of clusters. As soon cloud/AWS team changed the condition from clustered to non-clustered, it worked.

**Comment by QuanTran91** [comment]
So the rmq doest not support Redis in cluster mode? Do they?

**Comment by wellle** [comment]
Here's a related PR which is fairly close to complete. Maybe there's someone who could pick up this work and address the review comments so it can get merged? 🙏 
https://github.com/adjust/rmq/pull/128

**Comment by wellle** [comment]
Again I'm not sure if this is still a problem. Closing for now. Please reopen if the problem still persists :v:
