### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by rezaalimorady** [adjust/rmq#112]
```
taskConsumer := &TaskConsumer{}
name, err := taskQueue.AddConsumer("task-consumer", taskConsumer)
```

At your example i give error on `&TaskConsumer{}`.
Couldn't find that

![image](https://user-images.githubusercontent.com/60624937/153710584-2feef200-c7f7-44b1-a6d9-26d55cd627aa.png)

**Comment by wellle** [comment]
So `TaskConsumer` would be a struct you have to define on your own. And it needs to implement the `Consumer` interface so that you can use it in the `AddConsumer()` function. There are some examples of that in this repo.
