### ISSUE TITLE
When cleaner will move unacked queue to ready queue?

### ISSUE THREAD

**Issue by huanghantao** [adjust/rmq#119]
If my consumer is handling the delivery, and it will take a long time, is the cleanner going to move the delivery from the unacked queue to the ready queue?

**Comment by wellle** [comment]
No, the cleaner will not move any unacked deliveries as long as the consumer is still alive. Each consumer has its own heartbeat and the checker always checks the heartbeat and only cleans unacked deliveries of dead consumers.

**Comment by huanghantao** [comment]
I understand, thank you!
