### ISSUE TITLE
Add documnetation

### ISSUE THREAD

**Issue by sarim-zafar** [adjust/rmq#12]
Hi,
I stumbled upon you lib recently its been very helpful and i am very grateful that you have put such tremendous effort into making it but i find the documentation lacking for example i don't know how to assign a key to payload and receive its appropriate response from worker using the assigned id...
This is only one of the many problems i have stumbled upon.
I would be very grateful if you could add more documentation to readme file discussing various other functions
Regards,
Sarim

**Comment by kuangchanglang** [comment]
+1. expecting go-doc

**Comment by wellle** [comment]
I'm closing this as being pretty vague. Feel free to reopen with specific topics for which you feel like the documentation should be improved. :v:
