### ISSUE TITLE
delay queue function

### ISSUE THREAD

**Issue by 0xbillw** [adjust/rmq#129]
Is there a delay queue function? Or are there plans to support that feature?
Thank you!

**Comment by wellle** [comment]
Hey. I don't think we have exactly that. The way we approach this in our internal use is have our consumers sleep until a delivery is of certain age before it gets actually processed. For that your delivery needs to include something like a creation timestamp so you can check how old it is when the `Consume()` function gets called.

Additionally, for retries with delays we have push queues, see https://github.com/adjust/rmq#push-queues.

Hope that helps :v:
