### ISSUE TITLE
Is the queue thread-safe?

### ISSUE THREAD

**Issue by QuanTran91** [adjust/rmq#130]
Hi everyone,

In the document, in order to add message to the queue, we had to open the queue and then publish the message (as the code below)
taskQueue, err := connection.OpenQueue("tasks")
taskQueue.PublishBytes(byteData)

My question is: Should the queue be opened per request or can we share it among incoming requests (singleton)? 

Thanks.

**Comment by wellle** [comment]
Yes it is thread-safe and you can reuse Connection and Queue objects concurrently.
