### ISSUE TITLE
Any plan to implement BufferedQueue?

### ISSUE THREAD

**Issue by QuanTran91** [adjust/rmq#131]
Hi everyone,

In the repo: https://github.com/adjust/redismq , I saw you guys did implement the BufferedQueue to improve the performance of the queue.
However, now I don't see it anymore. At the moment I got an issue with the queue when there are a lot of requests coming, adding elements to the queue is quite slow.
Do you have any plans to bring BufferedQueue back?
Thank you.

**Comment by wellle** [comment]
I'm not aware of any plans for adding such behavior :v:

**Comment by wellle** [comment]
Closing as `won't fix`.
