### ISSUE TITLE
heartbeat is not stopped

### ISSUE THREAD

**Issue by KopiasCsaba** [adjust/rmq#142]
It seems, that upon closing up the rmq connection, a goroutine is leaked.

The reason seems to be, that there is nothing to stop the heartbeat if the queues and the client itself is closed.

There is a stopHeartbeat() method but it is private.

**Comment by wellle** [comment]
True. We should probably add a mechanism so once the closed connection is done with all pending internal work it would stop its own heartbeat.

**Comment by abarbalat** [comment]
In addition to leaked goroutine, its seems that we need to leak error channel, other wise it can panic, killing the process.
