### ISSUE TITLE
Is there task aggregating in rmq?

### ISSUE THREAD

**Issue by lakshy-amagi** [adjust/rmq#154]
I have implemented rmq for my projects. I need a task aggregator to aggregate tasks for some duration and then publish them to the queue.

**Comment by lakshy-amagi** [comment]
> Hey, there's no built in aggregation, but you can batch multiple deliveries yourself and then publish them all at once:
> 
> ```go
> queue.Publish(deliveries...)
> ```

Ooh okay will try, Is there any visualizer for rmq workers?

**Comment by wellle** [comment]
Not sure what exactly you mean, but there's this: https://github.com/adjust/rmq#statistics

**Comment by wellle** [comment]
Closing as resolved.
