### ISSUE TITLE
There isn't support to set and get headers in delivery interface

### ISSUE THREAD

**Issue by purush7** [adjust/rmq#160]
```
type Delivery interface {
	Payload() string

	Ack() error
	Reject() error
	Push() error
}

var (
	_ Delivery   = &redisDelivery{}
	_ WithHeader = &redisDelivery{}
)

type redisDelivery struct {
	ctx          context.Context
	payload      string
	clearPayload string
	header       http.Header
	unackedKey   string
	rejectedKey  string
	pushKey      string
	redisClient  RedisClient
	errChan      chan<- error
}

func (delivery *redisDelivery) Header() http.Header {
	return delivery.header
}

func (delivery *redisDelivery) String() string {
	return fmt.Sprintf("[%s %s]", delivery.clearPayload, delivery.unackedKey)
}

func (delivery *redisDelivery) Payload() string {
	return delivery.clearPayload
}
```
in [`delivery.go`](https://github.com/adjust/rmq/blob/e8bf6b59a0ee1b1beacc86d0c00d15c5e46b1169/delivery.go#L10C26-L10C26)

Why don't we have get and set headers support in delivery?
UseCase: We want to have a type of message in header. It also can be in payload but to get the type we need to do unmarshal it as payload will be in bytes.

I wanted to know the reasoning behind why the set and get for headers isn't present

**Comment by wellle** [comment]
Please see the example in the readme of how to set and get headers: 
https://github.com/adjust/rmq#header

**Comment by purush7** [comment]
@wellle Thanks for the quick reply
