### ISSUE TITLE
About pollDuration

### ISSUE THREAD

**Issue by hutu1st** [adjust/rmq#164]
Hi, my friend! 

Can there be a performance issue if I set pollDuration = 0 in order to make messages consumed in a timely manner?

**Comment by wellle** [comment]
Well it means that the poll goroutine always be checking for new messages without any waits. This may lead to high CPU usage even though there's no work available. See also https://en.wikipedia.org/wiki/Busy_waiting

**Comment by hutu1st** [comment]
got it, thanks!
