### ISSUE TITLE
Please provide a function for pause queue receive

### ISSUE THREAD

**Issue by xujinzheng** [adjust/rmq#2]
while I need gracefully shutdown worker, I shoud pause queue receive message first, but I found, the `queue.Close` is purge the queue messages, so I want rmq could provide an function for pause message receive, Thanks.

**Comment by wellle** [comment]
@xujinzheng: There is `queue.StopConsuming`. This should be what you're looking for. Please confirm.

**Comment by xujinzheng** [comment]
yes, but the interface of Queue did not define this function.

```go
type Queue interface {
	Publish(payload string) bool
	PublishBytes(payload []byte) bool
	SetPushQueue(pushQueue Queue)
	StartConsuming(prefetchLimit int, pollDuration time.Duration) bool
	AddConsumer(tag string, consumer Consumer) string
	AddBatchConsumer(tag string, batchSize int, consumer BatchConsumer) string
	PurgeReady() bool
	PurgeRejected() bool
	ReturnRejected(count int) int
	ReturnAllRejected() int
	Close() bool
}
```

**Comment by wellle** [comment]
@xujinzheng: I see. I added `QueueConsumer` to the interface in #3. Thank you :+1:

**Comment by xujinzheng** [comment]
You are move so fast, I plan to PR today. :+1:
