### ISSUE TITLE
Missing GetConsumers and RemoveConsumer from interface

### ISSUE THREAD

**Issue by chesleybrown** [adjust/rmq#26]
Is there any particular reason these two methods are missing from the interface? If not, can I do a PR to add them in?

- GetConsumers() []string https://github.com/adjust/rmq/blob/master/queue.go#L262
- RemoveConsumer(name string) bool https://github.com/adjust/rmq/blob/master/queue.go#L270

The Queue Interface
https://github.com/adjust/rmq/blob/master/queue.go#L32:L46

**Comment by wellle** [comment]
Being read only, I guess we could consider adding GetConsumers. Can you tell me how you'd like to use it?

But RemoveConsumer is probably not doing what you think it is. It just removes that name from the list where GetConsumers reads it from. It's not actually stopping a consumer from consuming. Please check the discussion in https://github.com/adjust/rmq/issues/5.

I'm just still not quite sure if a queue system actually needs to support killing consumers. Can't you design your consumers in a way that you can stop them yourself as needed?

**Comment by chesleybrown** [comment]
> It just removes that name from the list where GetConsumers reads it from. It's not actually stopping a consumer from consuming.

Ah, yes. I misunderstood then.

> Can't you design your consumers in a way that you can stop them yourself as needed?

Yes, I certainly can. Had originally thought that the _correct_ way would have been to call the `RemoveConsumer` to stop that consumer. I guess maybe you would recommend passing something like a Context to the consumer that we pass to `AddConsumer`?

Non-the-less I will take a closer look at #5 and #7. Thanks for the help!
