### ISSUE TITLE
Why a `uniuri` for each new consumer

### ISSUE THREAD

**Issue by oldaniel** [adjust/rmq#29]
So I planned to use this library for some notification stuff, but each time I restart the script my client gets a new name, so the name consists of `tag + 4 random characters` which prevents using the same queue again after a restart.

So what's the reason behind getting each time on a new connection a new unique name?

And could we make it a optional parameter?

**Comment by wellle** [comment]
@oldaniel: This random string only goes into the connection name. The idea is that you can deploy multiple instances of your consumer services using the same tag (like `my-worker`) and they would show up as `my-worker-GKc4T7`, `my-worker-HpPJiC` etc. So you can still recognize the consumer service by their tag which is included in the connection name, but we avoid name collisions by having different names for different instances/connections. That way you can also see how many services are currently running per tag.

Of course all of those instances can still use the same queues. Don't confuse queue names with connection names.

**Comment by oldaniel** [comment]
@wellle Ok that sounds correct. Thanks for the response.
