### ISSUE TITLE
redisConnection unexported ??

### ISSUE THREAD

**Issue by geekio** [adjust/rmq#40]
Was it done on purpose ? :)

**Comment by wellle** [comment]
Yes. You should never have to refer to it by specific type. Instead you should pass it around as `rmq.Connection`. That way you can actually use a `rmq.TestConnection` in tests without having to touch your code.

Or is there any case in which you'd actually need to refer to the specific type?

**Comment by geekio** [comment]
The case is pretty much typical. How can I normally share the same connection across different functions?

**Comment by wellle** [comment]
As I said, just pass it as `rmq.Connection`. For example:
```go
func main() {
	yourConnection := rmq.OpenConnection("your-tag", "tcp", "localhost:3456", 1)
	yourQueue := YourFunction(yourConnection)
}

func YourFunction(queueConnection rmq.Connection) rmq.Queue {
	return queueConnection.OpenQueue("your-queue")
}
```

**Comment by geekio** [comment]
Yeah, I looked it over, that's what I need, thank you!

**Comment by wellle** [comment]
Alright, I'll close this then 👍
