### ISSUE TITLE
How you you safely close the connection?

### ISSUE THREAD

**Issue by Xeoncross** [adjust/rmq#47]
What is the correct way to safely close the connection to redis while letting all the consumers (or producers) gracefully shutdown?

```
	connection := rmq.OpenConnection("email queue", "tcp", config.Redis.Address, 1)
	emailQueue := connection.OpenQueue("emails")
	emailQueue.StartConsuming(100, time.Microsecond)

	consumer := &queue.EmailConsumer{}
	emailQueue.AddConsumer("email consumer", consumer)

	done := make(chan bool)

	// Abort when we press CTRL+C (go run...) or send a kill -9 (go build...)
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
	go func() {
		for _ = range c {
			emailQueue.StopConsuming()
			connection.Close()
			done <- true
			log.Println("Interrupt / SIGTERM received. Stopping...")
		}
	}()

	<-done
```

**Comment by wellle** [comment]
This is currently not supported. There's some work in progress in https://github.com/adjust/rmq/pull/33. I just added a commit there to avoid the data race you mentioned in https://github.com/adjust/rmq/issues/48. Feel free to give that version a try, but I can't promise that we'll merge it soon.

**Comment by ghostsquad** [comment]
Looks like #33 has been merged. Is this still a problem?

**Comment by wellle** [comment]
You're right, this should be resolved now 👍
