### ISSUE TITLE
How do you submit from non-Go code?

### ISSUE THREAD

**Issue by Xeoncross** [adjust/rmq#49]
I'm trying to insert into the queue from a client not written in Go and having problems [figuring out the keys](https://github.com/adjust/rmq/blob/master/queue.go#L12) to use.

    LPUSH rmq::queue::[demo]::ready

Doesn't seem to be enough.

**Comment by wellle** [comment]
Well this seems to be enough. I just tested by running `/example/consumer/main.go` (with `batchSize = 1` at the top). Then every time I run
```
redis-cli -n 2 lpush rmq::queue::[things]::ready test
```
I see an output line like this:
```
2018/08/28 16:39:38 consumer0 consumed 1 test 0
```
Make sure you're connecting to the same Redis instance.

Also I'm not sure I would recommend such usage. There's no guarantee that the internal Redis key structure might change in the future, so this approach might break at some point.

**Comment by Xeoncross** [comment]
Thanks, I must be doing something else wrong then. I'll check the key/instance names.

I think I might just have go expose an HTTP interface that `.PublishBytes()` so any authenticated client can just dump stuff into the queue.
