### ISSUE TITLE
query on consumer

### ISSUE THREAD

**Issue by alext234** [adjust/rmq#51]
Just some questions on the usage:
- For `StartConsuming` if i give `prefetchLimit` a value greater than 1 and my consumer program crash does it mean those prefetched items will be lost?
- When I call `AddConsumer`, will each consumer be run in a separate goroutine?
- Also what will happen to those rejected? Go back to the queue?

**Comment by wellle** [comment]
- No, the if a consumer crashes the prefetched (unacked) deliveries remain in a separate list. The `rmq.Cleaner` can be used to return those unacked deliveries to the ready list, so other consumers can pick them up again.
- Yes, each consumer runs in its own goroutine.
- They go to the rejected list and stay there. In the queue stats handler you can see how many rejected deliveries you have per queue and then there are functions like `ReturnAllRejected()` to move rejected deliveries back to the ready list (for example after you fixed the consumer so you can handle those deliveries now).
