### ISSUE TITLE
How do you scale throughput?

### ISSUE THREAD

**Issue by thebiggestlebowski** [adjust/rmq#57]
What is the suggested approach to scale for throughput?

I am using rmq for a project which needs high throughput.  If I need to increase throughput from producer -> Q -> consumer, what is the recommended approach?  I am hoping for linear scalability - throw 2X more hardware, make it go 2X as fast (assuming I have a sufficient network bandwidth).

To give you an idea of the kind of throughput I hope to achieve: about 100K msgs/sec for a single Q.  Overall, I'm looking at about 10M msgs/sec in the system, so I already know I'll have 100 Q's.  Do I need to shard further?

1.  Add more boxes to the redis cluster.  Will that make rmq go faster?  This is the preferred approach since I can have a single, large Q.  My application semantics prefer a single, large, fast Q.

2.  Create N redis cluster and rmq queues.  Shard the Q traffic by the modulus of a hash of txn id.  I think I could get linear scalability here by simply having more redis clusters.   

3.  Some other approach I haven't thought of.  

4.  Are there some performance benchmarks you can point me to?

**Comment by wellle** [comment]
Hey, good question!

Generally I'd recommend to go with approach 1. as long as it helps. Making your cluster bigger can help separating the redis keys used for different hot queues. But once you reach throughput limits for one redis node based on a single hot queue only, adding more nodes won't help.

At that point approach 2. is good. If you can afford to add more clusters, this will allow you to scale further linearly.

But let me be honest here: At some point the overhead of maintaining all those redis clusters and sharding your infrastracture to make this work might become uncomfortable.

While I think rmq is a good fit for medium sized throughput with good ease of use, for high throughput use cases like your 10M/s, I might recommend using something like Kafka instead. (at least if you don't need the sharding anyway)

**Comment by thebiggestlebowski** [comment]
BTW, thank you for your answer.  Sorry it's taken me a while to say that ;)  We may be able to use RMQ since we only need 100K/sec because there are going to be N queues.  Kafka is another possibility.  We'll do performance/stress testing and see if rmq can handle the load reliably.
