### ISSUE TITLE
scaling questions

### ISSUE THREAD

**Issue by ghostsquad** [adjust/rmq#59]
Does this work when I have multiple different machines reading from the same queue? It looks like it might not based on examination of the code

**Comment by wellle** [comment]
Yes, it's safe to consume the same topic from multiple machines at the same time. Why do you think it wouldn't work?

**Comment by ghostsquad** [comment]
Oh, actually, I'm looking at the code again, and you are right. Sorry! I think I misread some code while I was looking at this on my phone.
