### ISSUE TITLE
Dead connection, consumer and handler in overview page I don't need

### ISSUE THREAD

**Issue by osenv** [adjust/rmq#66]
Hello,

I'm using docker for development. If I restart docker, the previous connections, consumers and handlers are no longer in need. But in the overview page, it shows as closed. I don't think this user-friendly. 

In my configuration, I only set one consumer. Each time I docker-compose down and docker-compose up -d, then there will be more one a dead connection, consumer and handler, which I don't need.

Is there any better way to handle this? Thanks.

![image](https://user-images.githubusercontent.com/4160306/61202996-b4c0ca80-a71b-11e9-8acd-eaf10ddc0d7c.png)

**Comment by wellle** [comment]
Hi @osenv. Yes, that's what the `Cleaner` is for. Please check where it's mentioned in the Readme. Basically you should have one cleaner instance running at all times to check for those dead connections and clean up the unacked deliveries of those consumers to be moved back to ready where new consumers can pick them up again.

There's also some conversation about the cleaner in https://github.com/adjust/rmq/pull/62. Hope that helps.

**Comment by wellle** [comment]
Nothing to be done here.
