### ISSUE TITLE
[Question] why I didn't see any key in redis?

### ISSUE THREAD

**Issue by seaguest** [adjust/rmq#69]
Hello,

Since this is a queue based on redis, should I see anything in redis when I check with 
```
KEYS *
```
but I didn't see anything, this confused me .

**Comment by wellle** [comment]
Hey! This should work, but you have to make sure you select the proper Redis database. For example if you run the producer example
```
cd example/producer
go run main.go
```
It will use redis db 2. See the last parameter passed into `OpenConnection`:
```go
connection := rmq.OpenConnection("producer", "tcp", "localhost:6379", 2)
```
So if you use `redis-cli`, then you need to first `select 2` before doing `keys *`. Or do it like this:
```
redis-cli -n 2 keys "*"
```

**Comment by seaguest** [comment]
thanks.
