### ISSUE TITLE
NewClient Error

### ISSUE THREAD

**Issue by vikrampunchh** [adjust/rmq#72]
cannot use "github.com/go-redis/redis".NewClient(&"github.com/go-redis/redis".Options literal) (type *"github.com/go-redis/redis".Client) as type *"gopkg.in/redis.v3".Client in argument to rmq.OpenConnectionWithRedisClient

**Comment by wellle** [comment]
This looks like you're using an old version. Most likely `v1.0.0`. Back then we expected a `redis.v3` client, now we expect a `go-redis/redis` client. Please either switch to the old `redis.v3` client or to the latest rmq version (master) and reopen if that didn't work 🤞
