### ISSUE TITLE
Support for batch publish ?

### ISSUE THREAD

**Issue by sakshamZomato** [adjust/rmq#73]
Hi,
Was wondering if there would be any support for `BulkPublishBytes` and the likes for other Publish method which would use the underlying Redis client's actual LPush signature as is (which is `LPush(key string, values ...interface{})`) ? If it's `string` in place of `interface{}`, that'd be awesome too ! 
If interested, I'm more than willing to help create a PR for this within the week.

**Comment by wellle** [comment]
@sakshamZomato: Thanks for the interest, feel free to open a PR 👍
