### ISSUE TITLE
cant connect remote redis via redis url

### ISSUE THREAD

**Issue by michaelchandrag** [adjust/rmq#77]
Hi, i can't connect to my Heroku Redis
```
url := redis://{user}:{password}@{host}:{port}

connection := rmq.OpenConnection("", "tcp", url, 1)
```

got this error
```
2020/03/15 14:33:40 rmq redis error is not nil dial tcp: address {the url}: too many colons in address
panic: rmq redis error is not nil dial tcp: address {the url}: too many colons in address

```

is there any bug and how to fix this?

Thank you

**Comment by wellle** [comment]
Seems to be an issue in `go-redis`. See https://github.com/go-redis/redis/issues/864#issuecomment-427737495:
> Use https://godoc.org/github.com/go-redis/redis#ParseURL
