### ISSUE TITLE
Support for Redis Streams

### ISSUE THREAD

**Issue by daemonfire300** [adjust/rmq#90]
https://redis.io/topics/streams-intro

Just a question, is support for redis streams planned?

**Comment by wellle** [comment]
No, I'm not aware of any plans related to that at this point. (But to be honest I haven't really looked into Redis streams yet)

**Comment by halink0803** [comment]
I think it would be great if rmq supports for Redis Streams. It would increase the lib performance.

**Comment by wellle** [comment]
This doesn't seem likely to be implemented any time soon. I'm closing it as `won't fix`. :v:
