### ISSUE TITLE
Update to use go-redis v8?

### ISSUE THREAD

**Issue by didip** [adjust/rmq#92]
Looks like rmq is not compatible with v8.

**Comment by fmstephe** [comment]
go-redis/redis/v8 doesn't have a stable release yet. All the tags that I can see are either alpha or beta. We will keep an eye open for the first stable release and upgrade then.

@didip if you see a stable v8 release please write a comment on this issue.

**Comment by igorrendulic** [comment]
I haven't checked the code if that would make sense but it might be a good idea to make it version agnostic?

**Comment by tsoslow** [comment]
It looks like they've released v8 and somehow are already to 8.2.x in less than 2 weeks.
