### ISSUE TITLE
compatibility with rsmq & rsmq_async

### ISSUE THREAD

**Issue by GopherJ** [adjust/rmq#93]
In nodejs [rsmq](https://github.com/smrchy/rsmq) is pretty popular, it has been ported to rust as [rsmq_async](https://docs.rs/rsmq_async/2.1.0/rsmq_async/).

For some reasons, I need to use rmq in golang, and use rust rsmq_async as a consumer, is it possible? I think it's pretty important for rmq to be compatible with other `redis message queue` implementations in other languages

**Comment by wellle** [comment]
This looks like it would have to be a major breaking change. I don't think this is going to happen anytime soon. At least I don't have the capacity to work on this.

**Comment by wellle** [comment]
Also closing as `won't fix` :v:
