### ISSUE TITLE
Use of redis.UniversalClient instead of Client for OpenConnectionWithRedisClient

### ISSUE THREAD

**Issue by stlimtat** [adjust/rmq#98]
redis-go now provides a UniversalClient for connection.  I will suggest removing the dependency on redis.Client, and replace that with redis.UniversalClient which covers the various aspects of client management from rmq.

**Comment by zxh** [comment]
Need this feature.

**Comment by wellle** [comment]
Sounds good. Anyone up for opening a PR for this?

**Comment by wellle** [comment]
This issue is fairly old and I'm not sure if it would be still worth implementing it. Please reopen if there are still benefits of switching to the other interface :v:
